ARG REPOSITORY
FROM navikey/raspbian-buster:latest as builder
# Update base install
#ADD sources.list /etc/apt/sources.list
#RUN apt-get update
#RUN apt-get install -y apt-utils
#RUN apt-get upgrade -y
#RUN apt-get install -y bash dialog e2fslibs e2fsprogs gcc-6-base gnupg gnupg-agent iproute2 libcomerr2 libdrm2 libgcc1 libgpg-error0 libncurses5 libncursesw5 libreadline7 libss2 libstdc++6 libsystemd0 libtinfo5 libudev1 login mount nano ncurses-base ncurses-bin pinentry-curses procps systemd udev util-linux wget
#RUN apt-get update

# create PI user
# pi:x:1000:1000:,,,:/home/pi:/bin/bash
RUN groupadd -g 1000 pi
RUN useradd -s /bin/bash -d /home/pi -u 1000 -g 1000 pi
RUN mkdir /home/pi
RUN chown -R pi:pi /home/pi
RUN echo 'pi:raspberry' | chpasswd
RUN usermod -a -G adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,input pi

# Clean up
RUN apt autoremove -y
RUN apt clean all

FROM navikey/raspbian-buster:latest
COPY --from=builder / /

